version: '2'
services:
  feel-admin:
    image: feel/admin
    ports:
      - "10086:10086"
    environment:
      - spring.profiles.active=dev
  feel-api:
    image: feel/api
    ports:
      - "10088:10088"
    environment:
      - spring.profiles.active=dev
